name: Zardosht Hodaie
markdown: redcarpet
pygments: true

excerpt_separator: "<!-- excerpt-separator -->"


# this goes inside _config.yml. Change as required
navigation:
- text: home
  path: index.html
  url: /index.html

- text: blog
  path: blog
  url: /blog.html

- text: فارسی
  path: farsi
  url: /farsi.html

- text: about
  path: about.html
  url: /about.html

- text: c.v.
  path: cv
  url: /files/cv.pdf